import { Translation } from './types';

export const TRANSLATIONS: Translation = {
  app_name: { en: 'Masar Flow', ar: 'مسار' },
  dashboard: { en: 'Dashboard', ar: 'الرئيسية' },
  create_new: { en: 'Create Workflow', ar: 'إنشاء مسار' },
  my_workflows: { en: 'My Workflows', ar: 'مساراتي' },
  public_workflows: { en: 'Public Library', ar: 'المكتبة العامة' },
  search_placeholder: { en: 'Search workflows...', ar: 'بحث في المسارات...' },
  step: { en: 'Step', ar: 'خطوة' },
  steps: { en: 'Steps', ar: 'خطوات' },
  start: { en: 'Start', ar: 'ابدأ' },
  continue: { en: 'Continue', ar: 'متابعة' },
  completed: { en: 'Completed', ar: 'مكتمل' },
  title: { en: 'Title', ar: 'العنوان' },
  description: { en: 'Description', ar: 'الوصف' },
  add_step: { en: 'Add Step', ar: 'إضافة خطوة' },
  save_workflow: { en: 'Save Workflow', ar: 'حفظ المسار' },
  ai_generate: { en: 'Generate with AI', ar: 'توليد بالذكاء الاصطناعي' },
  ai_prompt_placeholder: { en: 'e.g., How to change a car tire...', ar: 'مثلاً: كيفية تغيير إطار السيارة...' },
  type_text: { en: 'Text Instruction', ar: 'تعليمات نصية' },
  type_media: { en: 'Media', ar: 'وسائط' },
  type_gps: { en: 'Location (GPS)', ar: 'الموقع الجغرافي' },
  type_checklist: { en: 'Checklist', ar: 'قائمة تحقق' },
  open_maps: { en: 'Open in Maps', ar: 'فتح في الخرائط' },
  generating: { en: 'Generating...', ar: 'جاري التوليد...' },
  privacy: { en: 'Privacy', ar: 'الخصوصية' },
  private: { en: 'Private', ar: 'خاص' },
  public: { en: 'Public', ar: 'عام' },
  delete: { en: 'Delete', ar: 'حذف' },
  empty_state: { en: 'No workflows found. Create one!', ar: 'لا توجد مسارات. أنشئ واحداً!' },
  success_save: { en: 'Workflow saved successfully!', ar: 'تم حفظ المسار بنجاح!' },
  coordinates: { en: 'Coordinates', ar: 'الإحداثيات' },
  get_current_location: { en: 'Get Current Location', ar: 'تحديد موقعي الحالي' },
  upload_image: { en: 'Upload Image / Take Photo', ar: 'رفع صورة / التقاط صورة' },
  or_paste_url: { en: 'Or paste image URL', ar: 'أو الصق رابط صورة' },
  remove_image: { en: 'Remove Image', ar: 'حذف الصورة' },
  ai_option_search: { en: 'Use Online Search (More Accurate)', ar: 'بحث عبر الإنترنت (أكثر دقة)' },
  ai_option_media: { en: 'Suggest Images/Media', ar: 'اقتراح صور/وسائط' },
};